import type { NewTile } from "../database/repositories/tiles.js";

// SF-themed Monopoly-like board.
// Positions: 0..39 (40 tiles). Corner positions:
// - 0: GO
// - 9: Jail
// - 20: Free Parking
// - 29: Go To Jail
export const sfBoardTiles: NewTile[] = [
  { position: 0, name: "GO", tile_type: "go" },

  {
    position: 1,
    name: "Market Street",
    tile_type: "property",
    property_group: "brown",
    purchase_price: 60,
    rent_base: 2,
  },
  {
    position: 2,
    name: "Mission Street",
    tile_type: "property",
    property_group: "brown",
    purchase_price: 60,
    rent_base: 4,
  },
  { position: 3, name: "Chance", tile_type: "chance" },
  {
    position: 4,
    name: "Union Square",
    tile_type: "property",
    property_group: "light-blue",
    purchase_price: 100,
    rent_base: 6,
  },
  {
    position: 5,
    name: "Chinatown",
    tile_type: "property",
    property_group: "light-blue",
    purchase_price: 100,
    rent_base: 6,
  },
  { position: 6, name: "Community Chest", tile_type: "community_chest" },
  {
    position: 7,
    name: "Fisherman's Wharf",
    tile_type: "property",
    property_group: "light-blue",
    purchase_price: 120,
    rent_base: 8,
  },
  {
    position: 8,
    name: "Lombard Street",
    tile_type: "property",
    property_group: "pink",
    purchase_price: 140,
    rent_base: 10,
  },

  { position: 9, name: "Jail", tile_type: "jail" },

  {
    position: 10,
    name: "Golden Gate Park",
    tile_type: "property",
    property_group: "orange",
    purchase_price: 180,
    rent_base: 14,
  },
  { position: 11, name: "Chance", tile_type: "chance" },
  {
    position: 12,
    name: "Alcatraz Island",
    tile_type: "property",
    property_group: "orange",
    purchase_price: 180,
    rent_base: 14,
  },
  {
    position: 13,
    name: "Pier 39",
    tile_type: "property",
    property_group: "orange",
    purchase_price: 200,
    rent_base: 16,
  },
  {
    position: 14,
    name: "Coit Tower",
    tile_type: "property",
    property_group: "red",
    purchase_price: 220,
    rent_base: 18,
  },
  {
    position: 15,
    name: "Cable Car",
    tile_type: "railroad",
    purchase_price: 200,
    rent_base: 25,
  },
  {
    position: 16,
    name: "Twin Peaks",
    tile_type: "property",
    property_group: "red",
    purchase_price: 220,
    rent_base: 18,
  },
  { position: 17, name: "Community Chest", tile_type: "community_chest" },
  {
    position: 18,
    name: "Haight-Ashbury",
    tile_type: "property",
    property_group: "red",
    purchase_price: 240,
    rent_base: 20,
  },
  {
    position: 19,
    name: "Pacific Heights",
    tile_type: "property",
    property_group: "yellow",
    purchase_price: 260,
    rent_base: 22,
  },

  { position: 20, name: "Free Parking", tile_type: "free_parking" },

  {
    position: 21,
    name: "Castro District",
    tile_type: "property",
    property_group: "yellow",
    purchase_price: 260,
    rent_base: 22,
  },
  { position: 22, name: "Chance", tile_type: "chance" },
  {
    position: 23,
    name: "North Beach",
    tile_type: "property",
    property_group: "yellow",
    purchase_price: 280,
    rent_base: 24,
  },
  {
    position: 24,
    name: "Marina District",
    tile_type: "property",
    property_group: "green",
    purchase_price: 300,
    rent_base: 26,
  },
  {
    position: 25,
    name: "BART Station",
    tile_type: "railroad",
    purchase_price: 200,
    rent_base: 25,
  },
  {
    position: 26,
    name: "Presidio",
    tile_type: "property",
    property_group: "green",
    purchase_price: 300,
    rent_base: 26,
  },
  { position: 27, name: "Community Chest", tile_type: "community_chest" },
  {
    position: 28,
    name: "Golden Gate Bridge",
    tile_type: "property",
    property_group: "green",
    purchase_price: 320,
    rent_base: 28,
  },
  { position: 29, name: "Go To Jail", tile_type: "go_to_jail" },

  {
    position: 30,
    name: "SOMA",
    tile_type: "property",
    property_group: "dark-blue",
    purchase_price: 350,
    rent_base: 35,
  },
  {
    position: 31,
    name: "Financial District",
    tile_type: "property",
    property_group: "dark-blue",
    purchase_price: 350,
    rent_base: 35,
  },
  {
    position: 32,
    name: "Water Works",
    tile_type: "utility",
    purchase_price: 150,
    rent_base: 15,
  },
  {
    position: 33,
    name: "Embarcadero",
    tile_type: "property",
    property_group: "dark-blue",
    purchase_price: 400,
    rent_base: 50,
  },
  { position: 34, name: "Income Tax", tile_type: "tax" },
  {
    position: 35,
    name: "Muni",
    tile_type: "railroad",
    purchase_price: 200,
    rent_base: 25,
  },
  { position: 36, name: "Chance", tile_type: "chance" },
  {
    position: 37,
    name: "Nob Hill",
    tile_type: "property",
    property_group: "purple",
    purchase_price: 320,
    rent_base: 28,
  },
  { position: 38, name: "Luxury Tax", tile_type: "tax" },
  {
    position: 39,
    name: "Russian Hill",
    tile_type: "property",
    property_group: "purple",
    purchase_price: 350,
    rent_base: 35,
  },
];
